language: generic

before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  - unzip terraform_0.11.7_linux_amd64.zip
 
#These two steps will effectively validate our terraform and output a list of any changes to be made to our infrastructure
script:
 - chmod 777 deploy.sh
 - ./deploy.sh "$region" "$name" "$from_port" "$to_port" "$protocol" "$cidr_blocks"
